package Telas;

import java.sql.*;
import Conexao.ModuloConexao;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() {
        String sqlUsuario = "SELECT * FROM Usuario WHERE RA=? AND Senha=?";
        String sqlPontuacao = "SELECT * FROM Pontuacao WHERE RA=?";
        String sqlQuestoesRespondidas = "SELECT i.ID, r.usuario_ra, r.questao_id, r.resposta_dada "
                + "FROM Imagens i "
                + "LEFT JOIN Respostas r ON i.ID = r.questao_id AND r.usuario_ra = ?";

        try {
            // Consulta na tabela Usuario
            pst = conexao.prepareStatement(sqlUsuario);
            pst.setInt(1, Integer.parseInt(ctRA.getText()));
            pst.setString(2, ctSenha.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                String nome = rs.getString("Nome");
                int ra = rs.getInt("RA");

                // Consulta na tabela Pontuacao
                pst = conexao.prepareStatement(sqlPontuacao);
                pst.setInt(1, ra);
                rs = pst.executeQuery();

                if (rs.next()) {
                    int pontuacao = rs.getInt("Pontos");

                    // Consulta para obter informações sobre questões respondidas
                    pst = conexao.prepareStatement(sqlQuestoesRespondidas);
                    pst.setInt(1, ra);
                    rs = pst.executeQuery();

                    Set<Integer> questoesRespondidas = new HashSet<>();

                    while (rs.next()) {
                        int questaoID = rs.getInt("questao_ID");
                        questoesRespondidas.add(questaoID);
                    }

                    Inicial inicial = new Inicial();
                    inicial.setVisible(true);
                    Inicial.lblUsuario.setText(nome);
                    Inicial.lblPontuacao.setText(Integer.toString(pontuacao));
                    inicial.atualizarPontuacao(Integer.toString(pontuacao));

// Verificar questões respondidas e habilitar os botões apropriados
                    if (questoesRespondidas.contains(1) || questoesRespondidas.contains(2) || questoesRespondidas.contains(3) || questoesRespondidas.contains(4)) {
                        Inicial.btProb5.setEnabled(true);
                        Inicial.btProb6.setEnabled(true);
                        Inicial.btProb7.setEnabled(true);
                    }
                   if (questoesRespondidas.contains(5) || questoesRespondidas.contains(6) || questoesRespondidas.contains(7)) {
                        Inicial.btProb8.setEnabled(true);
                        Inicial.btProb9.setEnabled(true);
                        Inicial.btProb10.setEnabled(true);
                    }
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "RA e/ou Senha inválido(s)");
                }
            } else {
                JOptionPane.showMessageDialog(null, "RA e/ou Senha inválido(s)");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Principal() {
        initComponents();
        conexao = ModuloConexao.conector();
        System.out.println(conexao);

        if (conexao != null) {
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/dbokk.png")));

        } else {
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/dberro.png")));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ctRA = new javax.swing.JTextField();
        btLogin = new javax.swing.JButton();
        ctSenha = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("RA");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Senha");

        btLogin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/dberro.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(ctRA)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStatus))
                    .addComponent(ctSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(ctRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLogin)
                    .addComponent(lblStatus))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        logar();
    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    public static javax.swing.JTextField ctRA;
    private javax.swing.JPasswordField ctSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
